### ISSUE TITLE
Когнитивная лингвистика в ТГУ

### ISSUE THREAD

**Issue by amty** [amty/magister#2]
В [ТГУ](ТГУ.md) есть когнитивная лингвистика, и я не знаю, насколько она "когнитивная". Я её добавил, но предлагаю подумать об этом.

**Comment by jules-an** [comment]
ТГУ достаточно когнитивный сам по себе. Линк на курсы?

**Comment by jules-an** [comment]
В программе есть такие дисциплины, как "когнитивная психология" и "обработка лингвистической информации: язык и мозг". Вот [учебный план](http://www.tsu.ru/upload/iblock/b50/komp_i_kogn_lingv_up_2018.pdf)
Это определенно когнитивно, но, может быть, не очень психологично. Предлагаю оставить

**Comment by amty** [comment]
Да, я наверное путаю когнитивистику и когнитивную психологию. Зарождающаяся профдеформация?
